apiVersion: v1
kind: ReplicationController
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: noraimarm/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_URL
              value: http://134.209.142.62
            - name: LOCUSTFILE_PATH
              value: "./locustfile.py"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
