apiVersion: v1
kind: ReplicationController
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 10
  selector:
    name: locust
    role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: noraimarm/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_URL
              value: http://134.209.142.62
