apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  selector:
    name: locust
    role: master
  ports:
  - port: 8089
    targetPort: loc-master-web
    protocol: TCP
    name: loc-master-web
  - port: 5557
    targetPort: loc-master-p1
    protocol: TCP
    name: loc-master-p1
  - port: 5558
    targetPort: loc-master-p2
    protocol: TCP
    name: loc-master-p2
  type: LoadBalancer